### ISSUE TITLE
존재하지 않는 아이디를 검색했을 때 예외처리

### ISSUE THREAD

**Issue by blxckdog7702** [hmu332233/DailyCommitChecker#12]
현재는 존재하지 않는 아이디를 검색해도 검색이 되서 목록에 추가됩니다.

**Comment by hmu332233** [comment]
release: https://github.com/hmu332233/DailyCommitChecker/releases/tag/v.0.2.3
commit: https://github.com/hmu332233/DailyCommitChecker/commit/0966ae1bd9ce20b31389140dd83b559ffa1a86c9

에서 수정되었습니다.
